#!/usr/bin/env bash
var=0
while [ $var -lt 10 ]
do
    if [ $var -eq 3 ]
    then
	echo "bad luck"
    elif [ $var -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( var++ ))
done
